In [ ]:
# Manipulação de Dados com Pandas

import pandas as pd

In [ ]:
# DataFrame - df

# df_exemplo ou df_vendas ou df_pedidos

# importando um arquivo csv separado por virgula
# df = pd.read_csv('caminho+nomedoarquivo')

df = pd.read_csv('/content/drive/MyDrive/DATA PYHON 2604/datasets/base_vendas.csv')
print(df)

      matricula_funcionario Nome Funcionario     Cargo codigo_loja  \
0                 123456111       José Maria  Vendedor       CL001
1                 123456111       José Maria  Vendedor       CL001
2                 123456111       José Maria  Vendedor       CL001
3                 123456111       José Maria  Vendedor       CL001
4                 123456111       José Maria  Vendedor       CL001
...                     ...              ...       ...         ...
2995              123457113      Victor Hugo  Vendedor       CL004
2996              123457113      Victor Hugo  Vendedor       CL004
2997              123457113      Victor Hugo  Vendedor       CL004
2998              123457113      Victor Hugo  Vendedor       CL004
2999              123457113      Victor Hugo  Vendedor       CL004

        nome_loja  codigo_produto    descricao_produto         Categoria  \
0     Loja Matriz           10013                Fogão  Eletrodomésticos
1     Loja Matriz           10018              Colchão              Casa
2     Loja Matriz           10014            Geladeira  Eletrodomésticos
3     Loja Matriz           10001           Smartphone       Eletrônicos
4     Loja Matriz           10004  Máquina Lavar Roupa  Eletrodomésticos
...           ...             ...                  ...               ...
2995    Filial ES           10006      Aspirador de pó              Casa
2996    Filial ES           10011       Liquidificador           Cozinha
2997    Filial ES           10007            Batedeira           Cozinha
2998    Filial ES           10010  Fritadeira elétrica           Cozinha
2999    Filial ES           10004  Máquina Lavar Roupa  Eletrodomésticos

     preco_custo valor_unitario  quantidade comissao          dt_venda  \
0          210,9          404,1           1      NaN  28/09/2020 16:19
1          109,9          249,9           1      NaN  07/03/2020 12:47
2          699,9         1346,9           1      NaN  21/04/2019 10:48
3          899,9         1676,9           1      NaN  07/05/2020 17:59
4           1099         1709,1           1     0,05  14/08/2019 16:56
...          ...            ...         ...      ...               ...
2995        88,9          189,9           3      NaN  04/11/2019 15:40
2996        59,9          142,4           3      NaN  24/06/2019 09:04
2997        49,9           95,9           3      NaN  08/08/2020 14:46
2998       187,9            340           3      NaN  19/12/2019 09:21
2999        1099         1709,1           3     0,09  18/03/2019 15:40

            dt_entrega
0     05/10/2020 16:31
1     08/03/2020 12:47
2     23/04/2019 15:55
3     08/05/2020 14:31
4     19/08/2019 15:52
...                ...
2995  05/11/2019 10:40
2996  24/06/2019 10:50
2997  09/08/2020 14:07
2998  19/12/2019 10:51
2999  23/03/2019 17:52

[3000 rows x 14 columns]

In [ ]:
# Display - Mostra as 5 primeiras e 5 ultimas linhas do Dataframe
# caso o arquivo ja seja pequeno ele exibe todas as linhas

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [ ]:
# para escolhermos o separador, podemos usar:
# delimiter='separar' ou sep='separador'

df = pd.read_csv('/content/drive/MyDrive/DATA PYHON 2604/datasets/base_vendas_ponto_virgula.csv', sep=';')
display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",3,NaN,05/03/2020 12:58,11/03/2020 10:27
96,123456111,José Maria,Vendedor,CL001,Loja Matriz,10005,Notebook,Eletrônicos,"2299,9",3199,3,NaN,07/08/2020 13:11,07/08/2020 14:53
97,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",3,NaN,29/09/2019 09:05,29/09/2019 12:15
98,123456111,José Maria,Vendedor,CL001,Loja Matriz,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,30/09/2019 16:49,01/10/2019 14:55
99,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",3,NaN,08/11/2020 14:32,09/11/2020 09:48

In [ ]:
# importando um arquivo tsc (csv) separado por tabulação (\t)

df = pd.read_csv('/content/drive/MyDrive/DATA PYHON 2604/datasets/base_vendas_tab.tsv', sep='\t')

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",3,NaN,05/03/2020 12:58,11/03/2020 10:27
96,123456111,José Maria,Vendedor,CL001,Loja Matriz,10005,Notebook,Eletrônicos,"2299,9",3199,3,NaN,07/08/2020 13:11,07/08/2020 14:53
97,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",3,NaN,29/09/2019 09:05,29/09/2019 12:15
98,123456111,José Maria,Vendedor,CL001,Loja Matriz,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,30/09/2019 16:49,01/10/2019 14:55
99,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",3,NaN,08/11/2020 14:32,09/11/2020 09:48

In [ ]:
# importando um arquivo h5 (hdf)

df = pd.read_hdf('/content/drive/MyDrive/DATA PYHON 2604/datasets/base_vendas.h5')
display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",3,NaN,05/03/2020 12:58,11/03/2020 10:27
96,123456111,José Maria,Vendedor,CL001,Loja Matriz,10005,Notebook,Eletrônicos,"2299,9",3199,3,NaN,07/08/2020 13:11,07/08/2020 14:53
97,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",3,NaN,29/09/2019 09:05,29/09/2019 12:15
98,123456111,José Maria,Vendedor,CL001,Loja Matriz,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,30/09/2019 16:49,01/10/2019 14:55
99,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",3,NaN,08/11/2020 14:32,09/11/2020 09:48

In [ ]:
# importando um arquivo xml

df = pd.read_xml('/content/drive/MyDrive/DATA PYHON 2604/datasets/base_vendas.xml')
display(df)

,index,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,None,28/09/2020 16:19,05/10/2020 16:31
1,1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,None,07/03/2020 12:47,08/03/2020 12:47
2,2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,None,21/04/2019 10:48,23/04/2019 15:55
3,3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,None,07/05/2020 17:59,08/05/2020 14:31
4,4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,None,04/11/2019 15:40,05/11/2019 10:40
2996,2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,None,24/06/2019 09:04,24/06/2019 10:50
2997,2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,None,08/08/2020 14:46,09/08/2020 14:07
2998,2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,None,19/12/2019 09:21,19/12/2019 10:51
2999,2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [ ]:
# importando um arquivo json

df = pd.read_json('/content/drive/MyDrive/DATA PYHON 2604/datasets/base_vendas.json')
display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,None,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,None,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,None,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,None,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,None,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,None,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,None,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,None,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [ ]:
# importando um arquivo excel
# por padrão ele lê a primeira guia da pasta de trabalho

df = pd.read_excel('/content/drive/MyDrive/DATA PYHON 2604/datasets/Vendas.xlsx')
display(df)

    matricula_funcionario  Nome Funcionario
0               123456111        José Maria
1               123456111        José Maria
2               123456222  Maria das Graças
3               123456333      Jorge Mateus
4               123456555        Marta Cury
5               123456444     Ricardo Lemos
6               123456666   Reginaldo Sodré
7               123456999    Felipe Marinho
8               123456777     Marcos Coelho
9               123456888      Rita Sampaio
10              123457112    Mário Henrique
11              123457111       Pamela Lima
12              123457113       Victor Hugo

In [ ]:
# para ler outra guia, usamos o parâmetro 'sheet_name = nome_daguia'

df = pd.read_excel('/content/drive/MyDrive/DATA PYHON 2604/datasets/Vendas.xlsx', sheet_name='base_vendas')
display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,88.9,189.9,3,NaN,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,3,NaN,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,3,NaN,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,NaN,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00

In [ ]:
# verificando as guias que o arquivo contém:

planilhas = pd.read_excel('/content/drive/MyDrive/DATA PYHON 2604/datasets/Vendas.xlsx', sheet_name=None)
print(type(planilhas))
print(planilhas.keys())

<class 'dict'>
dict_keys(['funcionarios', 'base_vendas'])

In [ ]:
# importando arquivo html

tabelas = pd.read_html('/content/drive/MyDrive/DATA PYHON 2604/datasets/base_vendas.html')
print(type(tabelas)) # verificando o tipo
print(len(tabelas)) # contando os itens dessa lista

for i in tabelas:
    print(i)

df = tabelas[0]
display(df)

<class 'list'>
1
    matricula_funcionario Nome Funcionario     Cargo codigo_loja    nome_loja  \
0               123456111       José Maria  Vendedor       CL001  Loja Matriz
1               123456111       José Maria  Vendedor       CL001  Loja Matriz
2               123456111       José Maria  Vendedor       CL001  Loja Matriz
3               123456111       José Maria  Vendedor       CL001  Loja Matriz
4               123456111       José Maria  Vendedor       CL001  Loja Matriz
5               123456111       José Maria  Vendedor       CL001  Loja Matriz
6               123456111       José Maria  Vendedor       CL001  Loja Matriz
7               123456111       José Maria  Vendedor       CL001  Loja Matriz
8               123456111       José Maria  Vendedor       CL001  Loja Matriz
9               123456111       José Maria  Vendedor       CL001  Loja Matriz
10              123456111       José Maria  Vendedor       CL001  Loja Matriz
11              123456111       José Maria  Vendedor       CL001  Loja Matriz
12              123456111       José Maria  Vendedor       CL001  Loja Matriz
13              123456111       José Maria  Vendedor       CL001  Loja Matriz
14              123456111       José Maria  Vendedor       CL001  Loja Matriz
15              123456111       José Maria  Vendedor       CL001  Loja Matriz
16              123456111       José Maria  Vendedor       CL001  Loja Matriz
17              123456111       José Maria  Vendedor       CL001  Loja Matriz
18              123456111       José Maria  Vendedor       CL001  Loja Matriz
19              123456111       José Maria  Vendedor       CL001  Loja Matriz

    codigo_produto    descricao_produto         Categoria  preco_custo  \
0            10013                Fogão  Eletrodomésticos         2109
1            10018              Colchão              Casa         1099
2            10014            Geladeira  Eletrodomésticos         6999
3            10001           Smartphone       Eletrônicos         8999
4            10004  Máquina Lavar Roupa  Eletrodomésticos         1099
5            10010  Fritadeira elétrica           Cozinha         1879
6            10014            Geladeira  Eletrodomésticos         6999
7            10006      Aspirador de pó              Casa          889
8            10010  Fritadeira elétrica           Cozinha         1879
9            10017             Cama Box              Casa        11899
10           10003            Televisão  Eletrodomésticos        14009
11           10004  Máquina Lavar Roupa  Eletrodomésticos         1099
12           10018              Colchão              Casa         1099
13           10013                Fogão  Eletrodomésticos         2109
14           10016         Guarda Roupa              Casa         4899
15           10020           Impressora       Eletrônicos         3299
16           10017             Cama Box              Casa        11899
17           10008            Cafeteira           Cozinha         1599
18           10015           Microondas  Eletrodomésticos          189
19           10016         Guarda Roupa              Casa         4899

    valor_unitario  quantidade  comissao          dt_venda        dt_entrega
0             4041           1       NaN  28/09/2020 16:19  05/10/2020 16:31
1             2499           1       NaN  07/03/2020 12:47  08/03/2020 12:47
2            13469           1       NaN  21/04/2019 10:48  23/04/2019 15:55
3            16769           1       NaN  07/05/2020 17:59  08/05/2020 14:31
4            17091           1       5.0  14/08/2019 16:56  19/08/2019 15:52
5              340           1       NaN  10/07/2019 15:11  11/07/2019 14:30
6            13469           1       NaN  26/06/2019 11:03  28/06/2019 13:37
7             1899           1       NaN  15/03/2020 13:00  16/03/2020 11:15
8              340           1       NaN  15/08/2020 11:36  15/08/2020 14:22
9            18995           1       NaN  06/03/2019 13:01  11/03/2019 12:01
10          227999           1       NaN  11/10/2019 12:44  17/10/2019 14:58
11           17091           1       5.0  30/10/2019 17:22  03/11/2019 10:21
12            2499           1       NaN  28/05/2020 16:00  29/05/2020 14:16
13            4041           1       NaN  30/12/2019 15:07  04/01/2020 16:48
14             999           1       NaN  16/04/2019 09:22  23/04/2019 10:49
15            6741           1       NaN  07/09/2019 15:29  08/09/2019 13:00
16           18995           1       NaN  18/03/2019 09:08  25/03/2019 15:58
17            2849           1       NaN  28/01/2020 16:40  29/01/2020 11:59
18            3645           1       NaN  30/10/2020 17:27  31/10/2020 14:16
19             999           1       NaN  23/10/2020 17:41  30/10/2020 09:27

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,2109,4041,1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,1099,2499,1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,6999,13469,1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,8999,16769,1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,17091,1,5.0,14/08/2019 16:56,19/08/2019 15:52
5,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,1879,340,1,NaN,10/07/2019 15:11,11/07/2019 14:30
6,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,6999,13469,1,NaN,26/06/2019 11:03,28/06/2019 13:37
7,123456111,José Maria,Vendedor,CL001,Loja Matriz,10006,Aspirador de pó,Casa,889,1899,1,NaN,15/03/2020 13:00,16/03/2020 11:15
8,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,1879,340,1,NaN,15/08/2020 11:36,15/08/2020 14:22
9,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,11899,18995,1,NaN,06/03/2019 13:01,11/03/2019 12:01
10,123456111,José Maria,Vendedor,CL001,Loja Matriz,10003,Televisão,Eletrodomésticos,14009,227999,1,NaN,11/10/2019 12:44,17/10/2019 14:58
11,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,17091,1,5.0,30/10/2019 17:22,03/11/2019 10:21
12,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,1099,2499,1,NaN,28/05/2020 16:00,29/05/2020 14:16
13,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,2109,4041,1,NaN,30/12/2019 15:07,04/01/2020 16:48
14,123456111,José Maria,Vendedor,CL001,Loja Matriz,10016,Guarda Roupa,Casa,4899,999,1,NaN,16/04/2019 09:22,23/04/2019 10:49
15,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,3299,6741,1,NaN,07/09/2019 15:29,08/09/2019 13:00
16,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,11899,18995,1,NaN,18/03/2019 09:08,25/03/2019 15:58
17,123456111,José Maria,Vendedor,CL001,Loja Matriz,10008,Cafeteira,Cozinha,1599,2849,1,NaN,28/01/2020 16:40,29/01/2020 11:59
18,123456111,José Maria,Vendedor,CL001,Loja Matriz,10015,Microondas,Eletrodomésticos,189,3645,1,NaN,30/10/2020 17:27,31/10/2020 14:16
19,123456111,José Maria,Vendedor,CL001,Loja Matriz,10016,Guarda Roupa,Casa,4899,999,1,NaN,23/10/2020 17:41,30/10/2020 09:27

In [ ]:
# importando arquivo html

tabelas = pd.read_html('/content/drive/MyDrive/DATA PYHON 2604/datasets/Java_Wikipédia.html')
df = tabelas[0]
display(df)

,Java,Java.1
0,NaN,NaN
1,Paradigma,orientada a objetos estruturada imperativa gen...
2,Surgido em,23 de maio de 1995 (30 anos)
3,Última versão,25 (16 de setembro de 2025; há 6 meses[1])
4,Criado por,James Gosling Sun Microsystems
5,Estilo de tipagem,estática forte
6,Principais implementações,GCJ Javac
7,Influenciada por,Ada 83 C++ C#[2] Eiffel Generic Java Mesa Modu...
8,Influenciou,Ada 2005 BeanShell C#[3] Clojure D ECMAScript ...
9,Plataforma,ART Dalvik GraalVM HotSpot OpenJDK SuperWaba
10,Licença,GNU General Public License / Java Community Pr...
11,Extensão do arquivo,.java .class .jar .war
12,Página oficial,www.oracle.com/java/

In [ ]:
# conexão com banco de dados (sqlite)

import sqlite3

conn = sqlite3.connect('/content/drive/MyDrive/DATA PYHON 2604/datasets/vendas.db')

df = pd.read_sql_query("SELECT * FROM pedidos WHERE descricao_produto = 'Fogão'", conn)

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,,30/12/2019 15:07,04/01/2020 16:48
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,,05/11/2019 10:19,12/11/2019 15:30
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,,06/05/2020 15:04,11/05/2020 16:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",3,,15/10/2020 13:29,20/10/2020 10:55

In [ ]:
df2 = pd.read_sql_query('SELECT name FROM sqlite_schema WHERE type="table" ORDER BY name', conn)
display(df2)

      name
0  pedidos

In [ ]:
# instalar o conector MySQL
!pip install mysql_connector-Python

# importar a biblioteca
import mysql.connector

# conexão com o banco de dados MySQL
conexao = mysql.connector.connect(
    host="banco2604a.mysql.dbaas.com.br",
    user="banco2604a",
    password="Senai@2604",
    database="banco2604a"
)

print("\nConexão estabelecida com sucesso!\n")

# Criar um cursor
cursor = conexao.cursor()

# exemplo de SQL SELECT basico
cursor.execute('SELECT nome, email, cep FROM clientes_theo')

# capturar e exibir os resultados
print('Clientes cadastrados: \n')
for nome, email, cep in cursor.fetchall():
    print(f'Nome: {nome} - e-mail: {email} - CEP: {cep}')

# encerro o cursor e a conexão
cursor.close()
conexao.close()

Requirement already satisfied: mysql_connector-Python in /usr/local/lib/python3.12/dist-packages (9.6.0)

Conexão estabelecida com sucesso!

Clientes cadastrados:

Nome: ALEXANDRE THEO - e-mail: joao.silva@email.com - CEP: 10000001
Nome: MARIA OLIVEIRA - e-mail: maria.oliveira@email.com - CEP: 10000002
Nome: PEDRO SOUZA - e-mail: pedro.souza@email.com - CEP: 10000003
Nome: ANA COSTA - e-mail: ana.costa@email.com - CEP: 10000004
Nome: LUCAS ALMEIDA - e-mail: lucas.almeida@email.com - CEP: 10000005
Nome: CARLA RODRIGUES - e-mail: carla.rodrigues@email.com - CEP: 10000006
Nome: FERNANDO PEREIRA - e-mail: fernando.pereira@email.com - CEP: 10000007
Nome: JULIANA MARTINS - e-mail: juliana.martins@email.com - CEP: 10000008
Nome: RICARDO LIMA - e-mail: ricardo.lima@email.com - CEP: 10000009
Nome: PATRÍCIA MENDES - e-mail: patricia.mendes@email.com - CEP: 10000010
Nome: FÁBIO CARDOSO - e-mail: fabio.cardoso@email.com - CEP: 10000011
Nome: CAMILA GOMES - e-mail: camila.gomes@email.com - CEP: 10000012
Nome: RAFAEL DUARTE - e-mail: rafael.duarte@email.com - CEP: 10000013
Nome: VANESSA ROCHA - e-mail: vanessa.rocha@email.com - CEP: 10000014
Nome: EDUARDO ARAUJO - e-mail: eduardo.araujo@email.com - CEP: 10000015
Nome: SOFIA RIBEIRO - e-mail: sofia.ribeiro@email.com - CEP: 10000016
Nome: ANDRÉ NASCIMENTO - e-mail: andre.nascimento@email.com - CEP: 10000017
Nome: BEATRIZ SANTOS - e-mail: beatriz.santos@email.com - CEP: 10000018
Nome: MARCELO PIRES - e-mail: marcelo.pires@email.com - CEP: 10000019
Nome: FERNANDA CASTRO - e-mail: fernanda.castro@email.com - CEP: 10000020
Nome: THIAGO FERNANDES - e-mail: thiago.fernandes@email.com - CEP: 10000021
Nome: LARISSA MONTEIRO - e-mail: larissa.monteiro@email.com - CEP: 10000022
Nome: BRUNO FREITAS - e-mail: bruno.freitas@email.com - CEP: 10000023
Nome: ALINE LOPES - e-mail: aline.lopes@email.com - CEP: 10000024
Nome: DIEGO MORAES - e-mail: diego.moraes@email.com - CEP: 10000025
Nome: PAULA TEIXEIRA - e-mail: paula.teixeira@email.com - CEP: 10000026
Nome: RODRIGO BARROS - e-mail: rodrigo.barros@email.com - CEP: 10000027
Nome: NATÁLIA BATISTA - e-mail: natalia.batista@email.com - CEP: 10000028
Nome: FELIPE CUNHA - e-mail: felipe.cunha@email.com - CEP: 10000029
Nome: ISABELA CARVALHO - e-mail: isabela.carvalho@email.com - CEP: 10000030
Nome: GABRIEL DIAS - e-mail: gabriel.dias@email.com - CEP: 10000031
Nome: PRISCILA CORREIA - e-mail: priscila.correia@email.com - CEP: 10000032
Nome: ARNOLD STALONE - e-mail: arnold@warner.com - CEP: 10000050
Nome: TATIANE RAMOS - e-mail: tatiane.ramos@email.com - CEP: 10000034
Nome: MATEUS FARIA - e-mail: mateus.faria@email.com - CEP: 10000035
Nome: RENATA BARBOSA - e-mail: renata.barbosa@email.com - CEP: 10000036
Nome: OTÁVIO MELO - e-mail: otavio.melo@email.com - CEP: 10000037
Nome: LETÍCIA PRADO - e-mail: leticia.prado@email.com - CEP: 10000038
Nome: VITOR CUNHA - e-mail: vitor.cunha@email.com - CEP: 10000039
Nome: LUANA PAIVA - e-mail: luana.paiva@email.com - CEP: 10000040
Nome: MARCELA LUZ - e-mail: marcela.luz@email.com - CEP: 10000041
Nome: ALEXANDRE COSTA - e-mail: alexandre.costa@email.com - CEP: 10000042
Nome: DANIEL MOREIRA - e-mail: daniel.moreira@email.com - CEP: 10000043
Nome: MONIQUE BRAGA - e-mail: monique.braga@email.com - CEP: 10000044
Nome: CAIO PINTO - e-mail: caio.pinto@email.com - CEP: 10000045
Nome: JULIANA FURTADO - e-mail: juliana.furtado@email.com - CEP: 10000046
Nome: GUILHERME TORRES - e-mail: guilherme.torres@email.com - CEP: 10000047
Nome: PATRÍCIA GUIMARÃES - e-mail: patricia.guimaraes@email.com - CEP: 10000048
Nome: HUGO ALMEIDA - e-mail: hugo.almeida@email.com - CEP: 10000049
Nome: CAROLINA ASSIS - e-mail: carolina.assis@email.com - CEP: 10000050
Nome: JOANA COELHO - e-mail: joana.coelho@email.com - CEP: 10000051
Nome: MURILO BRAGA - e-mail: murilo.braga@email.com - CEP: 10000052
Nome: CLÁUDIA TELES - e-mail: claudia.teles@email.com - CEP: 10000053
Nome: SAMUEL CASTRO - e-mail: samuel.castro@email.com - CEP: 10000054
Nome: RAFAELA NEVES - e-mail: rafaela.neves@email.com - CEP: 10000055
Nome: ANDERSON PEIXOTO - e-mail: anderson.peixoto@email.com - CEP: 10000056
Nome: DÉBORA LINS - e-mail: debora.lins@email.com - CEP: 10000057
Nome: CRISTIANO PEIXOTO - e-mail: cristiano.peixoto@email.com - CEP: 10000058
Nome: MARIANA NOGUEIRA - e-mail: mariana.nogueira@email.com - CEP: 10000059
Nome: JÚLIO CESAR - e-mail: julio.cesar@email.com - CEP: 10000060
Nome: BIANCA LOPES - e-mail: bianca.lopes@email.com - CEP: 10000061
Nome: THIAGO VIEIRA - e-mail: thiago.vieira@email.com - CEP: 10000062
Nome: TATIANA REZENDE - e-mail: tatiana.rezende@email.com - CEP: 10000063
Nome: SÉRGIO OLIVEIRA - e-mail: sergio.oliveira@email.com - CEP: 10000064
Nome: MARCOS ARAÚJO - e-mail: marcos.araujo@email.com - CEP: 10000065
Nome: LUIZ HENRIQUE - e-mail: luiz.henrique@email.com - CEP: 10000066
Nome: HELENA CAMPOS - e-mail: helena.campos@email.com - CEP: 10000067
Nome: DENISE MARTINS - e-mail: denise.martins@email.com - CEP: 10000068
Nome: Peter Park - e-mail: igor.cardoso@email.com - CEP: 10000069
Nome: CRISTINA LIMA - e-mail: cristina.lima@email.com - CEP: 10000070
Nome: FABRÍCIO MENDES - e-mail: fabricio.mendes@email.com - CEP: 10000071
Nome: EMANUEL DUARTE - e-mail: emanuel.duarte@email.com - CEP: 10000072
Nome: SANDRA ROCHA - e-mail: sandra.rocha@email.com - CEP: 10000073
Nome: CLÁUDIO REZENDE - e-mail: claudio.rezende@email.com - CEP: 10000074
Nome: GISELE MORAES - e-mail: gisele.moraes@email.com - CEP: 10000075
Nome: DOUGLAS FERREIRA - e-mail: douglas.ferreira@email.com - CEP: 10000076
Nome: SILVIO SANTOS - e-mail: silvio@sbt.com.br - CEP: 10000050
Nome: NELSON CARVALHO - e-mail: nelson.carvalho@email.com - CEP: 10000078
Nome: ANDRÉ LUIZ - e-mail: andre.luiz@email.com - CEP: 10000079
Nome: KARINA DIAS - e-mail: karina.dias@email.com - CEP: 10000080
Nome: CÉSAR MOURA - e-mail: cesar.moura@email.com - CEP: 10000081
Nome: ROBERTA PRADO - e-mail: roberta.prado@email.com - CEP: 10000082
Nome: DANILO AZEVEDO - e-mail: danilo.azevedo@email.com - CEP: 10000083
Nome: EVELYN SILVA - e-mail: evelyn.silva@email.com - CEP: 10000084
Nome: MÁRCIO GOMES - e-mail: marcio.gomes@email.com - CEP: 10000085
Nome: TATIANA PIRES - e-mail: tatiana.pires@email.com - CEP: 10000086
Nome: VINÍCIUS NOGUEIRA - e-mail: vinicius.nogueira@email.com - CEP: 10000087
Nome: JEAN CLAUDE DA SILVA - e-mail: jean@claude.com - CEP: 10000050
Nome: GUSTAVO FARIA - e-mail: gustavo.faria@email.com - CEP: 10000089
Nome: PAULO ROBERTO - e-mail: paulo.roberto@email.com - CEP: 10000090
Nome: JULIO ANDRADE - e-mail: julio.andrade@email.com - CEP: 10000091
Nome: CÍNTIA OLIVEIRA - e-mail: cintia.oliveira@email.com - CEP: 10000092
Nome: ADRIANA MATOS - e-mail: adriana.matos@email.com - CEP: 10000093
Nome: RENATO CARDOSO - e-mail: renato.cardoso@email.com - CEP: 10000094
Nome: MELISSA COSTA - e-mail: melissa.costa@email.com - CEP: 10000095
Nome: MÁRIO TEIXEIRA - e-mail: mario.teixeira@email.com - CEP: 10000096
Nome: ELIANE RAMOS - e-mail: eliane.ramos@email.com - CEP: 10000097
Nome: SANDRO BATISTA - e-mail: sandro.batista@email.com - CEP: 10000098
Nome: VERÔNICA PINTO - e-mail: veronica.pinto@email.com - CEP: 10000099
Nome: HENRIQUE ROCHA - e-mail: henrique.rocha@email.com - CEP: 10000100

In [ ]:
# Instalar o conector MySQL
!pip install mysql-connector-Python


# importar a biblioteca
import mysql.connector


# conexão com o banco de dados MySQL
conexao = mysql.connector.connect(
    host="banco2604a.mysql.dbaas.com.br",
    user="banco2604a",
    password="Senai@2604",
    database="banco2604a"
)
print('👍Conexão estabelecida com sucesso\n')


# criar um cursor
cursor = conexao.cursor()


# exemplo de SQL SELECT básico
cursor.execute('SHOW TABLES')

# capturar e exibir os resultados
print('Tabelas da Base:\n')
for TABLE_NAME in cursor.fetchall():
    print(TABLE_NAME)

# capturar e exibir os resultados
print('Tabelas da Base:\n')
for TABLE_NAME in cursor.fetchall():
    print(TABLE_NAME)


# encerro o cursor e a conexão
cursor.close()
conexao.close()

print('👍Conexão encerrada com sucesso\n')

Requirement already satisfied: mysql-connector-Python in /usr/local/lib/python3.12/dist-packages (9.6.0)
👍Conexão estabelecida com sucesso

Tabelas da Base:

('ALUNOS_ABILIO',)
('Alunos_betas',)
('CEP_lucas20',)
('CEP_lucas31',)
('CLIENTES_CEP',)
('Cursoslima77',)
('IMOVEIS_ALO',)
('Pedidos_ceps',)
('Pedidos_cepwendel',)
('aluno_limonations',)
('aluno_mota',)
('alunos_alo10',)
('alunos_andre_oliveira',)
('alunos_becas',)
('alunos_becas10',)
('alunos_becas100',)
('alunos_becas2',)
('alunos_betas1001',)
('alunos_bruno',)
('alunos_diego_santos',)
('alunos_diego_santos10',)
('alunos_izabel',)
('alunos_izabel10',)
('alunos_lucas10',)
('alunos_lucas2',)
('alunos_lucassant10',)
('alunos_lucasteste',)
('alunos_mota02',)
('alunos_nferreira',)
('alunos_nferreira10',)
('alunos_nferreira100',)
('alunos_nferreira_100',)
('alunos_rhay',)
('alunos_rhay10',)
('alunos_rosana',)
('alunos_rosana10',)
('alunos_theo',)
('alunos_theo10',)
('alunos_willian',)
('cep_Projeto_willian',)
('cep_bitemculto',)
('cep_lucas10',)
('cep_rhay',)
('ceps',)
('ceps_alo',)
('ceps_bruno',)
('ceps_da_rhay',)
('ceps_diego_peixinho',)
('ceps_izabel',)
('ceps_mendel',)
('ceps_nferreira',)
('ceps_rosana',)
('ceps_theo',)
('ceps_wendel',)
('ceps_willian',)
('cliente_da_rhay',)
('clientes',)
('clientes_Projeto_willian',)
('clientes_alo',)
('clientes_bitemculto',)
('clientes_bruno',)
('clientes_da_rhay',)
('clientes_da_rhay2',)
('clientes_diego_peixinho',)
('clientes_izabel',)
('clientes_lucas10',)
('clientes_lucas20',)
('clientes_lucas31',)
('clientes_mendel',)
('clientes_nferreira',)
('clientes_por_estado_theo',)
('clientes_rhay',)
('clientes_rosana',)
('clientes_theo',)
('clientes_willian',)
('colaboradores',)
('colaboradores_bitemculto',)
('colaboradores_senai',)
('consulta_completa_bruno',)
('contratos',)
('contratos_Projeto_willian',)
('contratos_alo',)
('contratos_bruno',)
('contratos_diego_peixinho',)
('contratos_izabel',)
('contratos_lucas10',)
('contratos_nferreira',)
('contratos_rosana',)
('contratos_theo',)
('curso_lucas10',)
('curso_lucassant10',)
('curso_mota02',)
('cursos_abilio',)
('cursos_alo10',)
('cursos_andre_oliveira',)
('cursos_becas',)
('cursos_becas10',)
('cursos_becas100',)
('cursos_betas',)
('cursos_betas1001',)
('cursos_bruno',)
('cursos_diego_santos',)
('cursos_diego_santos10',)
('cursos_izabel',)
('cursos_izabel10',)
('cursos_lucas',)
('cursos_lucas10',)
('cursos_lucassant10',)
('cursos_lucasteste',)
('cursos_mota',)
('cursos_nferreira',)
('cursos_nferreira10',)
('cursos_nferreira100',)
('cursos_rhay',)
('cursos_rhay10',)
('cursos_rosana',)
('cursos_rosana10',)
('cursos_theo',)
('cursos_theo10',)
('cursos_willian',)
('empregados_alo',)
('empregados_izabel',)
('empregados_lucas10',)
('empregados_rosana',)
('imoveis',)
('imoveis_bruno',)
('imoveis_diego_peixinho',)
('imoveis_izabel',)
('imoveis_lucas10',)
('imoveis_nferreira',)
('imoveis_rosana',)
('imoveis_theo',)
('imovel_Projeto_willian',)
('logs__WILLIAN',)
('logs_alo',)
('logs_becas',)
('logs_bitemculto',)
('logs_bruno',)
('logs_diego_peixinho',)
('logs_diego_santos',)
('logs_izabel',)
('logs_lucas10',)
('logs_lucas20',)
('logs_nferreira',)
('logs_rhay',)
('logs_rosana',)
('logs_theo',)
('logs_wendel',)
('logs_willian',)
('matrculas_rosana10',)
('matricula_LIMAO',)
('matricula_lucas',)
('matricula_mota',)
('matricula_mota02',)
('matriculas_abilio',)
('matriculas_alo10',)
('matriculas_andre_oliveira',)
('matriculas_becas',)
('matriculas_becas10',)
('matriculas_becas100',)
('matriculas_betas',)
('matriculas_betas1001',)
('matriculas_bruno',)
('matriculas_diego_santos',)
('matriculas_diego_santos10',)
('matriculas_izabel',)
('matriculas_izabel10',)
('matriculas_lucasteste',)
('matriculas_nferreira',)
('matriculas_nferreira100',)
('matriculas_rhay',)
('matriculas_rhay10',)
('matriculas_rosana',)
('matriculas_theo',)
('matriculas_theo10',)
('matriculas_willian',)
('pedidos',)
('pedidos_WILLIAN',)
('pedidos_alo',)
('pedidos_bruno',)
('pedidos_cepmendel',)
('pedidos_diego_peixinho',)
('pedidos_izabel',)
('pedidos_lucas10',)
('pedidos_lucas11',)
('pedidos_lucas20',)
('pedidos_nferreira',)
('pedidos_rhay',)
('pedidos_rosana',)
('pedidos_theo',)
('produto_ceps',)
('produtos',)
('produtos_alo',)
('produtos_bitemculto',)
('produtos_bruno',)
('produtos_diego_peixinho',)
('produtos_izabel',)
('produtos_lucas10',)
('produtos_lucas12',)
('produtos_lucas20',)
('produtos_nferreira',)
('produtos_rhay',)
('produtos_rosana',)
('produtos_theo',)
('produtos_willian',)
('solicitacoes_bitemculto',)
('tabela_completa_bruno',)
('xcep',)
('xclientes',)
('xcontratos',)
('ximoveis',)
Tabelas da Base:

👍Conexão encerrada com sucesso

In [ ]:
## Instalar o conector MySQL e Pandas
!pip install mysql-connector-python pandas


## Importar bibliotecas
import mysql.connector
import pandas as pd


# conexão com o banco de dados MySQL
conexao = mysql.connector.connect(
    host="banco2604a.mysql.dbaas.com.br",
    user="banco2604a",
    password="Senai@2604",
    database="banco2604a"
)
print('👍Conexão estabelecida com sucesso\n')


## Criar cursor com dicionário
cursor = conexao.cursor(dictionary=True)


## 1️⃣ Pedidos de cada cliente
query = """
SELECT
    c.id_cliente,
    c.nome,
    c.email,
    p.id_pedido,
    pr.nome AS produto,
    p.quantidade,
    p.status,
    ce.cidade,
    ce.estado
FROM pedidos AS p
INNER JOIN clientes AS c ON p.id_cliente = c.id_cliente
INNER JOIN produtos AS pr ON p.id_produto = pr.id_produto
INNER JOIN ceps AS ce ON c.cep = ce.cep
ORDER BY c.nome;
"""
cursor.execute(query)
pedidos_clientes = pd.DataFrame(cursor.fetchall())
print("\n\n📌 Pedidos de cada cliente:")
display(pedidos_clientes)

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.12/dist-packages (9.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
👍Conexão estabelecida com sucesso



📌 Pedidos de cada cliente:

,id_cliente,nome,email,id_pedido,produto,quantidade,status,cidade,estado
0,93,Adriana Matos,adriana.matos@email.com,125,Roteador,1,CANCELADO,Casimiro de Abreu,RJ
1,42,Alexandre Costa,alexandre.costa@email.com,71,Teclado,7,CANCELADO,São José dos Campos,SP
2,24,Aline Lopes,aline.lopes@email.com,46,Relógio de Pulso,7,CANCELADO,Cuiabá,MT
3,24,Aline Lopes,aline.lopes@email.com,47,Máquina de Lavar Roupas,4,PAGO,Cuiabá,MT
4,4,Ana Costa,ana.costa@email.com,8,Cartão SD 64GB,2,PAGO,Porto Alegre,RS
...,...,...,...,...,...,...,...,...,...
127,62,Thiago Vieira,thiago.vieira@email.com,94,Secador de Roupas,2,PAGO,Gravataí,RS
128,14,Vanessa Rocha,vanessa.rocha@email.com,30,Correia para Câmera,1,PAGO,São Paulo,SP
129,99,Verônica Pinto,veronica.pinto@email.com,131,Cartão MicroSD 128GB,7,CANCELADO,Pau dos Ferros,RN
130,87,Vinícius Nogueira,vinicius.nogueira@email.com,119,Placa de Vídeo,2,PAGO,Itaboraí,RJ
131,39,Vitor Cunha,vitor.cunha@email.com,67,Jaqueta de Couro,8,PAGO,Campinas,SP

In [ ]:
# Instalar o conector MySQL
!pip install mysql-connector-Python


# importar a biblioteca
import mysql.connector


# conexão com o banco de dados MySQL
conexao = mysql.connector.connect(
    host="banco2604a.mysql.dbaas.com.br",
    user="banco2604a",
    password="Senai@2604",
    database="banco2604a"
)
print('👍Conexão estabelecida com sucesso\n')


# criar um cursor
cursor = conexao.cursor()


# exemplo de SQL SELECT básico
cursor.execute("UPDATE clientes_mendel SET nome = 'Alexandre Becas'")
cursor.execute("CREATE TABLE testepython ( codigo INT ) ")
conexao.commit()


# encerro o cursor e a conexão
cursor.close()
conexao.close()


print('👍Conexão encerrada com sucesso\n')

In [ ]:
# SALVANDO ARQUIVO CDV

df = pd.read_csv('/content/drive/MyDrive/DATA PYHON 2604/datasets/base_vendas.csv')

df.to_csv('/content/drive/MyDrive/DATA PYHON 2604/datasets/novo_arquivo_2604.csv')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/DATA PYHON 2604/datasets/novo_arquivo_2604.csv')

display(df)

,Unnamed: 0,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52